language: node_js

node_js:
- '0.10'

before_install:
- sudo add-apt-repository -y ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install --force-yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
